# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25592b3b77a1c700ff0b260c3d2a038c"
name = "the-storied-gift-ad-roa"
application_url = "https://amendments-xbox-advancement-disease.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ca3b4a52.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://amendments-xbox-advancement-disease.trycloudflare.com/auth/callback",
  "https://amendments-xbox-advancement-disease.trycloudflare.com/auth/shopify/callback",
  "https://amendments-xbox-advancement-disease.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
